#!/bin/sh

# Use neovim for vim if present.
alias vim="nvim" vimdiff="nvim -d" vi="nvim"

# Verbosity and settings that you pretty much just always are going to want.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"

# Colorize commands when possible.
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# Handy
alias v="$EDITOR"
alias t="tmux"
alias k="kubectl"
alias i="sudo apt install"
alias ii="sudo apt remove"
alias u="sudo apt update"
alias uu="sudo apt upgrade -y"
alias uuu="u && uu"
alias ssleep='sudo shutdown -h '
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias octal="stat -c '%a %A %n'"
alias untargz="tar -xvzf"
alias szsh="source ~/.config/zsh/.zshrc"
alias todo="vi ~/TODO.md"

## cfg
alias bashrc='nvim ~/.bashrc'
alias zshrc='nvim ~/.config/zsh/.zshrc'
alias aliasrc='nvim ~/.config/aliasrc'
alias profile='nvim ~/.profile'
alias vimrc='nvim ~/.config/nvim/init.lua'
alias i3config='nvim ~/.config/i3/config'
alias polybarconf='nvim ~/.config/polybar/config'
alias tmuxconf='nvim ~/.tmux.conf.local'
alias redshiftconf='nvim ~/.config/redshift.conf'
alias aptlist='dpkg --get-selections | fzf'

## git
alias ggpull='git pull origin `git_branch`'
alias ggpush='git push origin `git_branch`'
alias gc='git commit -S -v'
alias gc!='git commit -v --amend'
alias gs='git status -s'
alias gss='git status -s'
alias gd='git diff'
alias ga='git add'
alias gcheck='git_checkout'

## yadm
alias yss='yadm status -s'
alias ya='yadm add'
alias yc='yadm commit -S -v'
alias yd='yadm diff'
alias yypush='yadm push origin master'
